name: Test

on:
  push

env:
  BUILD_URL: 'https://github.comm/reload/poc-dpl-react-pr-trigger/releases/download/john'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Testing
        run: |
          echo "BRANCH_EXISTS=$(git show-ref --quiet refs/heads/abe && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Testing II
        run: |
          echo "${{ toJson(env) }}"
